### ISSUE TITLE
In NPC module, clicking 'add lair action' crashes the program.

### ISSUE THREAD

**Issue by Maasq** [kay9911/FG5EParser#9]
FG5EParser has stopped working

A problem caused the program to stop working correctly... standard windows 10 dialogue. I'm running Win10 (not Creator yet). No other 'add' button causes this crash.

**Comment by kay9911** [comment]
Ack. Will be fixed in the next version.

**Comment by kay9911** [comment]
@Maasq I have implemented it in alpha-v0.2.
